import type { Metadata } from "next";
import { Marcellus } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const marcellus = Marcellus({
  variable: "--font-marcellus-sans",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${marcellus.variable} antialiased`}>
        {" "}
        <Header />
        {children}
      </body>
    </html>
  );
}
